#PANDAS TUTORIAL

Agenda
    1. What is data frames?
    2. What is Data Series?
    3. Different operations in Pandas
  

In [1]:
##import pandas package
import pandas as pd
import numpy as np

In [4]:
df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['R1','R2','R3','R4','R5'],columns=['C1','C2','C3','C4'])

In [5]:
df.head()

C1  C2  C3  C4
R1   0   1   2   3
R2   4   5   6   7
R3   8   9  10  11
R4  12  13  14  15
R5  16  17  18  19

In [6]:
##create an excel
df.to_csv('Test1.csv')

In [7]:
df.loc()

In [8]:
df.loc('R1')

ValueError: No axis named R1 for object type DataFrame

In [10]:
df.loc['R1']

C1    0
C2    1
C3    2
C4    3
Name: R1, dtype: int32

In [12]:
type(df.loc['R1'])

pandas.core.series.Series

In [13]:
df.iloc[:,:]

C1  C2  C3  C4
R1   0   1   2   3
R2   4   5   6   7
R3   8   9  10  11
R4  12  13  14  15
R5  16  17  18  19

In [14]:
df.iloc[0:2,0:2]

C1  C2
R1   0   1
R2   4   5

In [16]:
df.iloc[:,1:]

C2  C3  C4
R1   1   2   3
R2   5   6   7
R3   9  10  11
R4  13  14  15
R5  17  18  19

In [19]:
df.loc['R1']['C2']

1

In [20]:
type(df.loc['R1']['C2'])

numpy.int32

In [21]:
type(df.iloc[:,1:])

pandas.core.frame.DataFrame

In [22]:
#convert dataframes to arrays
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [23]:
df.iloc[:,1:].values.shape

(5, 3)

In [25]:
#check nulls
df.isnull().sum()

C1    0
C2    0
C3    0
C4    0
dtype: int64

In [27]:
#check unique counts
df['C1'].value_counts()

0     1
4     1
8     1
12    1
16    1
Name: C1, dtype: int64

In [28]:
df['C1'].unique()

array([ 0,  4,  8, 12, 16])

In [35]:
print(df['C1'])

print(type(df['C1']))

## if needed to put multiple columns from a data frame then list[]
print(df[['C1','C2']])

print(type(df[['C1','C2']]))

R1     0
R2     4
R3     8
R4    12
R5    16
Name: C1, dtype: int32
<class 'pandas.core.series.Series'>
    C1  C2
R1   0   1
R2   4   5
R3   8   9
R4  12  13
R5  16  17
<class 'pandas.core.frame.DataFrame'>


In [37]:
##reading file
df = pd.read_csv('mercedesbenz.csv')

In [38]:
df.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [42]:
df.shape

(4209, 378)

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB


In [45]:
df.describe() ##only integer and floating columns

ID            y          X10     X11          X12  \
count  4209.000000  4209.000000  4209.000000  4209.0  4209.000000   
mean   4205.960798   100.669318     0.013305     0.0     0.075077   
std    2437.608688    12.679381     0.114590     0.0     0.263547   
min       0.000000    72.110000     0.000000     0.0     0.000000   
25%    2095.000000    90.820000     0.000000     0.0     0.000000   
50%    4220.000000    99.150000     0.000000     0.0     0.000000   
75%    6314.000000   109.010000     0.000000     0.0     0.000000   
max    8417.000000   265.320000     1.000000     0.0     1.000000   

               X13          X14          X15          X16          X17  ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.057971     0.428130     0.000475     0.002613     0.007603  ...   
std       0.233716     0.494867     0.021796     0.051061     0.086872  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     1.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              X375         X376         X377         X378         X379  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.318841     0.057258     0.314802     0.020670     0.009503   
std       0.466082     0.232363     0.464492     0.142294     0.097033   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              X380         X382         X383         X384         X385  
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  
mean      0.008078     0.007603     0.001663     0.000475     0.001426  
std       0.089524     0.086872     0.040752     0.021796     0.037734  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 370 columns]

In [46]:
df['X0'].value_counts()

z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
m      34
ai     34
e      32
ba     27
at     25
a      21
ax     19
aq     18
am     18
i      18
u      17
aw     16
l      16
ad     14
au     11
k      11
b      11
r      10
as     10
bc      6
ao      4
c       3
aa      2
q       2
ac      1
g       1
ab      1
Name: X0, dtype: int64

In [47]:
df[df['y']>100]

ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
0        0  130.81   k  v  at  a  d   u  j  o  ...     0     0     1     0   
6       24  128.76  al  r   e  f  d   f  h  s  ...     0     0     0     0   
8       27  108.67   w  s  as  e  d   f  i  h  ...     1     0     0     0   
9       30  126.99   j  b  aq  c  d   f  a  e  ...     0     0     1     0   
10      31  102.09   h  r   r  f  d   f  h  p  ...     0     0     0     0   
...    ...     ...  .. ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...   
4202  8402  123.34  ap  l   s  c  d  aa  d  r  ...     0     0     0     0   
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0   
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0   
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0   
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
0        0     0     0     0     0     0  
6        0     0     0     0     0     0  
8        0     0     0     0     0     0  
9        0     0     0     0     0     0  
10       0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
4202     0     0     0     0     0     0  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[2004 rows x 378 columns]

In [48]:
df.corr()

ID         y       X10  X11       X12       X13       X14  \
ID    1.000000 -0.055108  0.001602  NaN  0.058988 -0.031917 -0.025438   
y    -0.055108  1.000000 -0.026985  NaN  0.089792  0.048276  0.193643   
X10   0.001602 -0.026985  1.000000  NaN -0.033084 -0.028806 -0.100474   
X11        NaN       NaN       NaN  NaN       NaN       NaN       NaN   
X12   0.058988  0.089792 -0.033084  NaN  1.000000  0.214825 -0.246513   
...        ...       ...       ...  ...       ...       ...       ...   
X380 -0.013577  0.040932 -0.010479  NaN -0.005566  0.023045  0.007743   
X382 -0.038171 -0.159815 -0.010164  NaN -0.024937 -0.021713  0.012713   
X383 -0.009332  0.040291 -0.004740  NaN -0.011628 -0.010125  0.023604   
X384 -0.015355 -0.004591 -0.002532  NaN -0.006212  0.041242  0.025199   
X385  0.029059 -0.022280 -0.004387  NaN -0.010765 -0.009373  0.043667   

           X15       X16       X17  ...      X375      X376      X377  \
ID    0.002237 -0.036480 -0.038171  ...  0.045229 -0.080259 -0.022965   
y     0.023116  0.048946 -0.159815  ...  0.029100  0.114005  0.061403   
X10  -0.002532 -0.005944 -0.010164  ...  0.165277 -0.028618 -0.074244   
X11        NaN       NaN       NaN  ...       NaN       NaN       NaN   
X12  -0.006212 -0.014584 -0.024937  ... -0.107864 -0.070214  0.030134   
...        ...       ...       ...  ...       ...       ...       ...   
X380 -0.001968 -0.004619 -0.007899  ... -0.061741 -0.022240 -0.061168   
X382 -0.001908 -0.004480  1.000000  ... -0.059883 -0.021571 -0.059327   
X383 -0.000890 -0.002089 -0.003572  ... -0.015413 -0.010059  0.035107   
X384 -0.000475 -0.001116 -0.001908  ... -0.014917 -0.005373  0.008694   
X385 -0.000824 -0.001934 -0.003307  ...  0.055225 -0.009311 -0.025610   

          X378      X379      X380      X382      X383      X384      X385  
ID    0.030371  0.023382 -0.013577 -0.038171 -0.009332 -0.015355  0.029059  
y    -0.258679  0.067919  0.040932 -0.159815  0.040291 -0.004591 -0.022280  
X10  -0.016870 -0.011374 -0.010479 -0.010164 -0.004740 -0.002532 -0.004387  
X11        NaN       NaN       NaN       NaN       NaN       NaN       NaN  
X12  -0.016043 -0.027907 -0.005566 -0.024937 -0.011628 -0.006212 -0.010765  
...        ...       ...       ...       ...       ...       ...       ...  
X380 -0.013110 -0.008839  1.000000 -0.007899 -0.003683 -0.001968 -0.003410  
X382 -0.012716 -0.008573 -0.007899  1.000000 -0.003572 -0.001908 -0.003307  
X383 -0.005930 -0.003998 -0.003683 -0.003572  1.000000 -0.000890 -0.001542  
X384 -0.003168 -0.002136 -0.001968 -0.001908 -0.000890  1.000000 -0.000824  
X385 -0.005489 -0.003701 -0.003410 -0.003307 -0.001542 -0.000824  1.000000  

[370 rows x 370 columns]

In [49]:
df['X11'].value_counts()

0    4209
Name: X11, dtype: int64

In [50]:

lst_data=[[1,2,3],[3,4,np.nan],[5,6,np.nan],[np.nan,np.nan,np.nan]]

In [51]:
df=pd.DataFrame(lst_data)

In [52]:
df.head()

0    1    2
0  1.0  2.0  3.0
1  3.0  4.0  NaN
2  5.0  6.0  NaN
3  NaN  NaN  NaN

In [53]:
##Handling missing values

df.isnull()

0      1      2
0  False  False  False
1  False  False   True
2  False  False   True
3   True   True   True

In [54]:
df.isnull().sum()

0    1
1    1
2    3
dtype: int64

In [59]:
##drop nan values
df.dropna(axis=0)

0    1    2
0  1.0  2.0  3.0

In [60]:
df = pd.DataFrame(np.random.randn(5, 3), index=['a', 'c', 'e', 'f', 'h'],
                     columns=['one', 'two', 'three'])

In [61]:
df.head()

one       two     three
a  0.226459 -0.625682 -0.202160
c -0.764919  1.510051 -0.577925
e -0.659255 -1.771201 -0.475716
f -0.932780 -0.661533 -1.430718
h  1.568363  1.489807 -1.194782

In [62]:

df2=df.reindex(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])

In [64]:
df2

one       two     three
a  0.226459 -0.625682 -0.202160
b       NaN       NaN       NaN
c -0.764919  1.510051 -0.577925
d       NaN       NaN       NaN
e -0.659255 -1.771201 -0.475716
f -0.932780 -0.661533 -1.430718
g       NaN       NaN       NaN
h  1.568363  1.489807 -1.194782

In [65]:
df2.dropna(axis=0)

one       two     three
a  0.226459 -0.625682 -0.202160
c -0.764919  1.510051 -0.577925
e -0.659255 -1.771201 -0.475716
f -0.932780 -0.661533 -1.430718
h  1.568363  1.489807 -1.194782

In [66]:
pd.isna(df2['one'])

a    False
b     True
c    False
d     True
e    False
f    False
g     True
h    False
Name: one, dtype: bool

In [67]:
df2.fillna('missing')

one       two     three
a  0.226459 -0.625682  -0.20216
b   missing   missing   missing
c -0.764919  1.510051 -0.577925
d   missing   missing   missing
e -0.659255 -1.771201 -0.475716
f  -0.93278 -0.661533 -1.430718
g   missing   missing   missing
h  1.568363  1.489807 -1.194782

In [71]:
df2['one'].values

array([ 0.22645926,         nan, -0.76491867,         nan, -0.659255  ,
       -0.93278013,         nan,  1.56836349])